version: "3.5"

services:
  webserver:
    container_name: medialibrary-webserver
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/home/medial/application
  mysql:
    container_name: medialibrary-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: medial_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3385:3306"
    expose:
      # Opens port 3306 on the container
      - '3385'
